// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SifflForums.Data;

namespace SifflForums.Data.Migrations
{
    [DbContext(typeof(SifflContext))]
    [Migration("20190605205154_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("SifflForums.Data.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CommentThreadId");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<int>("ModifiedBy");

                    b.Property<string>("Text");

                    b.Property<int>("UserId");

                    b.HasKey("CommentId");

                    b.HasIndex("CommentThreadId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SifflForums.Data.Entities.CommentThread", b =>
                {
                    b.Property<int>("CommentThreadId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<int>("ModifiedBy");

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.Property<int>("UserId");

                    b.HasKey("CommentThreadId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("UserId");

                    b.ToTable("CommentThreads");
                });

            modelBuilder.Entity("SifflForums.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName");

                    b.Property<string>("Email");

                    b.Property<DateTime>("RegisteredAtUtc");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SifflForums.Data.Entities.Comment", b =>
                {
                    b.HasOne("SifflForums.Data.Entities.CommentThread", "CommentThread")
                        .WithMany()
                        .HasForeignKey("CommentThreadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SifflForums.Data.Entities.CommentThread", b =>
                {
                    b.HasOne("SifflForums.Data.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
