// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SifflForums.Data;

namespace SifflForums.Data.Migrations
{
    [DbContext(typeof(SifflContext))]
    [Migration("20190830065358_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("SifflForums.Data.Entities.BlacklistedPassword", b =>
                {
                    b.Property<int>("BlacklistedPasswordId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.HasKey("BlacklistedPasswordId");

                    b.ToTable("BlacklistedPasswords");
                });

            modelBuilder.Entity("SifflForums.Data.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<int>("ModifiedBy");

                    b.Property<int>("SubmissionId");

                    b.Property<string>("Text");

                    b.Property<int>("UserId");

                    b.Property<int>("VotingBoxId");

                    b.HasKey("CommentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("UserId");

                    b.HasIndex("VotingBoxId")
                        .IsUnique();

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SifflForums.Data.Entities.ForumSection", b =>
                {
                    b.Property<int>("ForumSectionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<int>("CreatedBy");

                    b.Property<string>("Description");

                    b.Property<bool>("IsPrivate");

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<int>("ModifiedBy");

                    b.Property<string>("Name");

                    b.HasKey("ForumSectionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("ForumSections");

                    b.HasData(
                        new
                        {
                            ForumSectionId = 1,
                            CreatedAtUtc = new DateTime(2019, 8, 30, 6, 53, 57, 703, DateTimeKind.Utc).AddTicks(6023),
                            CreatedBy = 1,
                            Description = "General Discussions",
                            IsPrivate = false,
                            ModifiedAtUtc = new DateTime(2019, 8, 30, 6, 53, 57, 703, DateTimeKind.Utc).AddTicks(6988),
                            ModifiedBy = 1,
                            Name = "General"
                        });
                });

            modelBuilder.Entity("SifflForums.Data.Entities.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<int>("CreatedBy");

                    b.Property<int>("ForumSectionId");

                    b.Property<DateTime>("ModifiedAtUtc");

                    b.Property<int>("ModifiedBy");

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.Property<int>("UserId");

                    b.Property<int>("VotingBoxId");

                    b.HasKey("SubmissionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ForumSectionId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("UserId");

                    b.HasIndex("VotingBoxId")
                        .IsUnique();

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            SubmissionId = 1,
                            CreatedAtUtc = new DateTime(2019, 8, 30, 6, 53, 57, 704, DateTimeKind.Utc).AddTicks(2425),
                            CreatedBy = 1,
                            ForumSectionId = 1,
                            ModifiedAtUtc = new DateTime(2019, 8, 30, 6, 53, 57, 704, DateTimeKind.Utc).AddTicks(2434),
                            ModifiedBy = 1,
                            Text = "Simple Forums for Learning",
                            Title = "Welcome to Siffl Forums",
                            UserId = 1,
                            VotingBoxId = 1
                        });
                });

            modelBuilder.Entity("SifflForums.Data.Entities.Upvote", b =>
                {
                    b.Property<int>("UpvoteId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserId");

                    b.Property<int>("VotingBoxId");

                    b.Property<int>("Weight");

                    b.HasKey("UpvoteId");

                    b.HasAlternateKey("VotingBoxId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Upvotes");
                });

            modelBuilder.Entity("SifflForums.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<DateTime>("LastPasswordResetUtc");

                    b.Property<string>("Password");

                    b.Property<DateTime>("RegisteredAtUtc");

                    b.Property<string>("Salt");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "system@example.com",
                            LastPasswordResetUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "suchAPrettyHouse",
                            RegisteredAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salt = "suchAPrettyGarden",
                            Username = "System"
                        });
                });

            modelBuilder.Entity("SifflForums.Data.Entities.VotingBox", b =>
                {
                    b.Property<int>("VotingBoxId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("VotingBoxId");

                    b.ToTable("VotingBoxes");

                    b.HasData(
                        new
                        {
                            VotingBoxId = 1
                        });
                });

            modelBuilder.Entity("SifflForums.Data.Entities.Comment", b =>
                {
                    b.HasOne("SifflForums.Data.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.Submission", "Submission")
                        .WithMany("Comments")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.VotingBox", "VotingBox")
                        .WithMany()
                        .HasForeignKey("VotingBoxId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SifflForums.Data.Entities.ForumSection", b =>
                {
                    b.HasOne("SifflForums.Data.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SifflForums.Data.Entities.Submission", b =>
                {
                    b.HasOne("SifflForums.Data.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.ForumSection", "ForumSection")
                        .WithMany()
                        .HasForeignKey("ForumSectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.VotingBox", "VotingBox")
                        .WithMany()
                        .HasForeignKey("VotingBoxId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SifflForums.Data.Entities.Upvote", b =>
                {
                    b.HasOne("SifflForums.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SifflForums.Data.Entities.VotingBox", "VotingBox")
                        .WithMany("Upvotes")
                        .HasForeignKey("VotingBoxId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
